### ISSUE TITLE
Does this app obsolete Chatter?

### ISSUE THREAD

**Issue by warpech** [Starcounter/Timeline#9]
If this app contains `CalculatePatchAndPushOnWebSocket` on newly added notes (meaning that new notes on the timeline are pushed to all users looking at the timeline), then it obsoletes the [Chatter](https://github.com/StarcounterApps/Chatter) app and Chatter can be deleted.

@bouguila can you please check?

**Comment by bouguila** [comment]
yes sure!

**Comment by bouguila** [comment]
@warpech the actual version of `Timeline` is not using `Session.CalculatePatchAndPushOnWebSocket` to push freshly created notes. 
As far as i know, `Timeline` is intended to display events managed in the Calendar app and not to broadcast messages or notes whereas `Chatter` stands for broadcasting messages to other users looking to a same chatroom. 
On the other hand `Timeline` and `Notes` are hard-coded to each other and working as single app. So why are they standing as separated apps and or instance `Calendar` app allows the creation of notes without any extra app.
So in my opinion `notes` is the obsolete here and thus should be deleted.

**Comment by warpech** [comment]
I agree with everything said here.

Notes app should be replaced with some small editable view from the Contents app.

But the point of asking about Chatter. Chatter pushes messages to all people looking at a Chat Room (aka Chat Group). Similarly, Timeline could push events to all people looking at a specific timeline, based on a combination of commit hooks and `Session.CalculatePatchAndPushOnWebSocket`.

WDYT?

**Comment by bouguila** [comment]
well, if the purpose of Chatter is just pushing messages to a Chat Room then it can be considered as a sub feature of the timeline app on events of type text notes, and then chat rooms will be just the scope of the current object timeline (Person, Organization, Something, etc.)

**Comment by warpech** [comment]
I have created an issue for `CalculatePatchAndPushOnWebSocket`: https://github.com/StarcounterApps/Timeline/issues/15

Chatter that uses Timeline for rendering becomes really indifferent from [Notes](https://github.com/StarcounterApps/notes), so I think we should remove Chatter and keep Timeline + Notes.

WDYT?

**Comment by bouguila** [comment]
that's a great idea! this will entail a valuable improvement to Timeline App and also one less app to worry about.

**Comment by Joltrix** [comment]
Are we sure we want to remove Chatter?

The only thing Notes and Chatter have in common is their behavior when run together with the Timeline app.

But isn't Chatter supposed to "cover" more than that? For example being able to create chat rooms and groups, and being able to directly chat with someone else. Whereas Notes are pretty much just a "Timeline memo".

In that case, wouldn't it be more reasonable to remove Notes? Since it has a much smaller area of use?

Alternatively improve Notes, so that it's not as similar to Chatter. If notes for example functions more like a "WordPad", and can be used in a similar way as google docs, or as a "notification" keeper for example. Then they would work rather differently.

**Comment by Joltrix** [comment]
@warpech We discussed the Chatter app briefly during one of the weekly meetings while you've been away on vacation. Though, we didn't decide on anything. So I'd like to hear your opinion on the matter.

What do you think we should do about the Chatter app? I am currently making the Notes app work independently, so that it will become a real app, and not only an "add-on" to the Timeline, by making it more similar to Google Keep.

Which makes Chatter and Notes quite different. Should we perhaps improve the Chatter app and make it more similar an actual chat program? By making it a real chat? Cause I can imagine that a "chat app" would be something that a lot of customers want to/can use. If we also add in functionality to write personal messages to people / see online status of people in your group/company/friends list etc. Or should we leave the Chatter app for now, and come back to it sometime in the future?
